In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [9]:
df_train = pd.read_csv("./dataset/train.csv")
df_fullfilment = pd.read_csv("./dataset/fulfilment_center_info.csv")
df_meal = pd.read_csv("./dataset/meal_info.csv")

In [10]:
print(f"Train data: {df_train.shape}")
print(f"Fullfilment_center_info data: {df_fullfilment.shape}")
print(f"Meal_info data: {df_meal.shape}")

Train data: (456548, 9)
Fullfilment_center_info data: (77, 5)
Meal_info data: (51, 3)

In [11]:
df_train.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders
0,1379560,1,55,1885,136.83,152.29,0,0,177
1,1466964,1,55,1993,136.83,135.83,0,0,270
2,1346989,1,55,2539,134.86,135.86,0,0,189
3,1338232,1,55,2139,339.50,437.53,0,0,54
4,1448490,1,55,2631,243.50,242.50,0,0,40

In [7]:
df_fullfilment.head()

   center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [8]:
df_meal.head()

   meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai
3     1248  Beverages  Indian
4     2631  Beverages  Indian

In [7]:
data.describe()

,ApplicantIncome,CoapplicantIncome,Credit_History,LoanAmount,Loan_Amount_Term
count,981.000000,981.000000,902.000000,954.000000,961.000000
mean,5179.795107,1601.916330,0.835920,142.511530,342.201873
std,5695.104533,2718.772806,0.370553,77.421743,65.100602
min,0.000000,0.000000,0.000000,9.000000,6.000000
25%,2875.000000,0.000000,1.000000,100.000000,360.000000
50%,3800.000000,1110.000000,1.000000,126.000000,360.000000
75%,5516.000000,2365.000000,1.000000,162.000000,360.000000
max,81000.000000,41667.000000,1.000000,700.000000,480.000000

In [8]:
data.isnull().sum()

ApplicantIncome        0
CoapplicantIncome      0
Credit_History        79
Dependents            25
Education              0
Gender                24
LoanAmount            27
Loan_Amount_Term      20
Loan_ID                0
Loan_Status          367
Married                3
Property_Area          0
Self_Employed         55
dtype: int64

In [9]:
len(test)

367

In [10]:
data['Dependents'].value_counts()

0     545
1     160
2     160
3+     91
Name: Dependents, dtype: int64

In [11]:
dependent_loanstatus = data.groupby(by = ['Dependents', 'Loan_Status']).agg({'Loan_ID':'count'})
dependent_loanstatus
# plt.figure(figsize = (10,10))
# plt

                        Loan_ID
Dependents Loan_Status
0          N                107
           Y                238
1          N                 36
           Y                 66
2          N                 25
           Y                 76
3+         N                 18
           Y                 33